name: Check localization file endings

on: [push]

jobs:
  check_localization_file_endings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - name: "Run script"
        run: |
          mkdir CK3_Validator
          git clone https://github.com/LT-Rascek/CK3_Validator.git CK3_Validator
          python3 CK3_Validator/test_scripts/check_localization_file_endings.py "."
